org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft / Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
# Tu peux remplacer par la derniere 47.x listee sur files.minecraftforge.net
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings officiels Mojang
mapping_channel=official
mapping_version=1.20.1

# Mod
mod_id=missilemod
mod_name=MissileMod - Arsenal militaire
mod_license=All Rights Reserved
mod_version=1.3.0
mod_group_id=fr.missilemod
mod_authors=MissileMod
mod_description=Missiles (Grad, Tomahawk, Scud, strategique), artillerie animee M777 et mortier, mines, grenades fumigenes, sous-munitions, frappe aerienne et alerte anti-missile.
